/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative */

#ifndef _Included_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
#define _Included_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1init
  (JNIEnv *, jobject);

/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _open
 * Signature: (JLcom/google/android/exoplayer2/ext/ffmpeg/bridge/OutputWriter;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1open
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _codecInit
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1codecInit
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _decode
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1decode
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint);

/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _getChannelCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1getChannelCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _getSampleRate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1getSampleRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _reset
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1reset
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative
 * Method:    _release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_google_android_exoplayer2_ext_ffmpeg_bridge_FfmpegNative__1release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
